# Generated by Django 3.2.2 on 2021-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('upcoming', models.BooleanField(blank=True, null=True)),
                ('launch_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('launch_date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('rocket', models.CharField(blank=True, max_length=50, null=True)),
                ('launch_site', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(default='test')),
                ('image_url', models.CharField(blank=True, max_length=50, null=True)),
                ('article_url', models.CharField(blank=True, max_length=50, null=True)),
                ('wikipedia_url', models.CharField(blank=True, max_length=50, null=True)),
                ('video_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
