# Generated by Django 3.2.2 on 2021-05-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='launch_year',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='upcoming',
        ),
    ]
