# Generated by Django 3.2.2 on 2021-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210508_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='image_alt_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
