# Generated by Django 3.2.2 on 2021-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_launch_image_alt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='launch_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='succeeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='upcoming',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
