# Generated by Django 3.2.2 on 2021-05-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210509_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
