# Generated by Django 3.2.2 on 2021-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_launch_launch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='article_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
