# Generated by Django 3.2.2 on 2021-05-09 20:10

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210509_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='video_url',
        ),
        migrations.AddField(
            model_name='launch',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
