# Generated by Django 3.2.2 on 2021-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210509_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launch',
            options={'verbose_name_plural': 'launches'},
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
