# Generated by Django 3.2.2 on 2021-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210510_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
